server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka}

spring:
  application:
    name: odyssey
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: forge
          uri: lb://forge
          predicates:
            - Path=/users/**, /moderator/**, /educations/**, /initiatives/**
        - id: lore
          uri: lb://lore
          predicates:
            - Path=/documents/**
management:
  endpoints:
    web:
      exposure:
        include: "*"